# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-08 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('released_year', models.IntegerField(default=0)),
                ('rating', models.FloatField(default=0)),
                ('genres', models.CharField(max_length=120)),
            ],
        ),
    ]
