# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-10 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moviedata', '0003_auto_20180909_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_id',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
